# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopStories' do
  use_frameworks!

  # Pods for TopStories
  pod 'SDWebImage'

  target 'TopStoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
